[package]
name = "rs_lib"
version = "0.1.0"
authors = ["WiggidyW"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = { version = "^4" }