CREATE TABLE Omdb (
	imdbID INTEGER PRIMARY KEY,
	response BOOLEAN NOT NULL,
	timestamp REAL NOT NULL,
	year TEXT NOT NULL,
	title TEXT NOT NULL,
	type TEXT NOT NULL,
	ratings TEXT,
	imdbRating REAL,
	totalSeasons INTEGER,
	imdbVotes INTEGER,
	metascore INTEGER,
	seriesID INTEGER,
	episode INTEGER,
	season INTEGER,
	production TEXT,
	boxOffice TEXT,
	language TEXT,
	released TEXT,
	director TEXT,
	runtime TEXT,
	country TEXT,
	website TEXT,
	writer TEXT,
	actors TEXT,
	awards TEXT,
	poster TEXT,
	rated TEXT,
	genre TEXT,
	plot TEXT,
	dvd TEXT
);